image:
  file: .gitpod.Dockerfile

tasks:
  - before: >
      pip3 install -e . &&
      export COCOTB_REDUCED_LOG_FMT=1
    init: >
      cd /workspace/uvm-python/test/examples/simple/registers/models/fifo_reg/ &&
      gp open dut.sv &&
      gp open dut.vhd &&
      gp open Makefile &&
      gp open tb_env.py &&
      gp open tb_run.py &&
      make SIM=icarus &&
      make SIM=ghdl TOPLEVEL_LANG=vhdl &&
      make SIM=verilator &
    command: >
      cd /workspace/uvm-python/test/examples/simple/registers/models/fifo_reg/ ;
      history -s make SIM=icarus ;
      history -s make SIM=ghdl TOPLEVEL_LANG=vhdl ;
      history -s make SIM=verilator ;
      history -d 3

# NOTE: the geometry for gtkwave's fullscreen size can be found with xwininfo -root

# https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080  # VNC for e.g. gtkwave
    onOpen: notify
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - mshr-h.veriloghdl@1.0.6:RPslnvyzniF7C66mxHT+Hg==
    - puorc.awesome-vhdl@0.0.1:w0lXwxIDreee5Mbtg9XSfg==
